# -*- coding: utf-8 -*-
"""Practice01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ph5H05PAHeJSK3x_ZXi-dMdRlCjX7Fm

# Phase 1 – Conditional Thinking (If–Else, Boolean Logic)

---
## Level 1: Simple Conditions (Getting started)

----

###1. Take a number and print whether it’s positive, negative, or zero.
"""

x = int(input("Enter the number: "))
if x > 0:
  print("Positive")
elif x < 0:
  print("Negative")
else:
  print("Zero")

"""### 2. Check if a number is even or odd.


"""

x = int(input("Enter the number: "))
# print( "Even" if x%2 == 0 else "Odd" )
y = lambda x : "Even" if x%2 == 0  else "Odd"
print(y(x))

"""### 3. Check if a number is divisible by 5.

"""

x = int(input("Enter the number: "))
y = lambda x : "Yes" if x%5 == 0 else "No"
print(y(x))

"""### 4. Check if a number is divisible by both 3 and 5.

"""

x = int(input("Enter the number: "))
y = lambda x : "Yes" if x%3 == 0 and x%5 == 0 else "No"
print(y(x))

"""### 5. Check if a given year is a leap year."""

x = int(input("Enter the number: "))
if (x%4 == 0 and x%100 != 0) or ( x%400 == 0 ):
  print("Leap year")
else:
  print("Not leap year")

"""### 6. Take two numbers and print the larger one."""

x = int(input("Enter the number x: "))
y = int(input("Enter the number y: "))
# if x>y:
#   print(x)
# else:
#   print(y)
z = lambda x,y : x if x>y else y
print(z(x,y))

"""### 7. Take three numbers and print the largest."""

x =  int(input("Enter the number x: "))
y =  int(input("Enter the number y: "))
z = int(input("Enter the number z: "))
if x>y and x>z:
  print(x)
elif y>x and y>z:
  print(y)
else:
  print(z)

"""#### 8. Take a temperature value and print “Cold”, “Warm”, or “Hot” using range conditions."""

x =  int(input("Enter the temperature : "))
if x in range(30,50):
  print("Hot")
elif x in range(20,30):
  print("Warm")
else:
  print("Cold")

# One line code
# print("Cold" if (x := int(input("Enter temperature: "))) < 15 else "Warm" if x <= 25 else "Hot")

"""### 9. Take a character and check if it’s a vowel or consonant."""

print("Vowel" if (x:= (input("Enter the aplhapet :"))) in ["a","e","i","o","u","A","E","I","O","U"] else "Consonant")
# Using lower
print("Vowel" if (x:= (input("Enter the aplhapet :").lower())) in ["a","e","i","o","u"] else "Consonant")

"""### 10. Take a character and check whether its uppercase, lowercase, a digit, or a special character"""

ch = input("Enter the character: ")
if ch.islower():
  print("Lower")
elif ch.isupper():
  print("Uppercase")
elif ch.isdigit():
  print("Digit")
else:
  print("Special Character")